"""add_api_keys_table

Revision ID: f7111a21954a
Revises: add_eval_created_by
Create Date: 2026-06-23 17:01:27.278952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7111a21954a'
down_revision = 'add_eval_created_by'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
        sa.Column('id', sa.UUID(), nullable=False, comment='API Key ID'),
        sa.Column('owner_id', sa.UUID(), nullable=False, comment='所属用户ID'),
        sa.Column('name', sa.String(length=128), nullable=False, comment='Key名称，如OA系统集成'),
        sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='Key前缀，用于展示和日志'),
        sa.Column('key_hash', sa.String(length=255), nullable=False, comment='Key哈希（bcrypt）'),
        sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='权限范围列表'),
        sa.Column('rate_limit_rpm', sa.Integer(), nullable=False, comment='每分钟请求上限'),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间'),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间'),
        sa.Column('is_active', sa.BOOLEAN(), nullable=False, comment='是否激活'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
